const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const {pathToFileURL}=require("node:url"),{chromium}=require("playwright"),root=path.resolve(__dirname,"../.."),read=(file)=>fs.readFileSync(path.join(root,file),"utf8");
assert.equal(read("index.html"),read("cmt-quiz.html"));
for(const asset of ["lead-placement/module.css","lead-placement/content.js","lead-placement/module.js"])assert(read("index.html").includes(asset));
assert(read("index.html").indexOf("ecg-study/content.js")<read("index.html").indexOf("lead-placement/content.js"));assert(read("index.html").indexOf("lead-placement/content.js")<read("index.html").indexOf("ecg-study/module.js"));
const ctx={};vm.runInNewContext(read("lead-placement/content.js")+";this.data=LEAD_PLACEMENT;",ctx);const D=JSON.parse(JSON.stringify(ctx.data));
assert.deepEqual(D.chestSequence,["v1","v2","v4","v3","v5","v6"]);const positions=Object.fromEntries(D.leads.map((lead)=>[lead.id,lead.placement]));
assert.match(positions.v1,/4th intercostal space, right sternal border/i);assert.match(positions.v2,/4th intercostal space, left sternal border/i);assert.match(positions.v4,/5th intercostal space, left midclavicular line/i);assert.match(positions.v3,/Halfway between V2 and V4/i);assert.match(positions.v5,/left anterior axillary line, same horizontal level as V4/i);assert.match(positions.v6,/left midaxillary line, same horizontal level as V4/i);
assert.equal(D.cards.length,18);assert.equal(new Set(D.cards.map((card)=>card.id)).size,18);
for(const [id,pattern] of [["lead-i",/RA\(−\) → LA\(\+\)/],["lead-ii",/RA\(−\) → LL\(\+\)/],["lead-iii",/LA\(−\) → LL\(\+\)/],["lead-avr",/right arm/i],["lead-avl",/left arm/i],["lead-avf",/left foot/i],["plane-limb",/Frontal plane/i],["plane-chest",/Transverse plane/i]])assert(D.cards.some((card)=>card.id===id&&pattern.test(card.definition)));
for(const type of ["tap","identify","location-to-lead","lead-to-location","plane","bipolar","augmented"])assert(D.quiz.some((q)=>q.type===type));for(const q of D.quiz){if(q.type==="tap")assert(D.leads.some((lead)=>lead.id===q.target));else{assert.equal(q.options.length,4);assert(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4);}assert(q.explain.length>30);}
const manifest=JSON.parse(read("lead-placement/assets/model-manifest.json"));assert.equal(manifest.license,"CC BY 4.0");assert.equal(manifest.source.bytes,5931700);assert.equal(manifest.source.triangles,185314);assert.equal(manifest.optimized.bytes,2410628);assert.equal(manifest.optimized.triangles,92656);assert.equal(manifest.optimized.extensionsUsed.length,0);assert.match(read("lead-placement/assets/ATTRIBUTION.md"),/HuBMAP Human Reference Atlas/i);assert.match(read("lead-placement/assets/ATTRIBUTION.md"),/CC BY 4\.0/i);assert.match(read("lead-placement/assets/ATTRIBUTION.md"),/teaching overlays/i);assert(fs.statSync(path.join(root,"lead-placement/assets/torso-model-data.js")).size>3200000);

(async()=>{const launch={headless:true,args:["--use-angle=swiftshader","--enable-unsafe-swiftshader"]};if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH)launch.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;const browser=await chromium.launch(launch),page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[],requests=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",m=>{if(m.type()==="error")errors.push(m.text());});page.on("request",r=>requests.push(r.url()));fs.mkdirSync(path.join(root,"review-lead-placement"),{recursive:true});
try{await page.goto(pathToFileURL(path.join(root,"index.html")).href);assert(!requests.some(url=>/torso-model-data|torso-3d/.test(url)));assert(await page.locator("#leadPlacementLaunch").isVisible());assert.match(await page.locator("#leadPlacementLaunch").innerText(),/3D torso, landmarks, chest leads, limb leads, flashcards & quiz/);await page.locator("#leadPlacementLaunch").click();await page.waitForSelector('#lead3DHost[data-ready="true"]',{timeout:30000});const host=page.locator("#lead3DHost");assert.equal(await host.getAttribute("data-triangles"),"92656");assert.equal(await host.getAttribute("data-markers"),"10");assert.equal(await host.getAttribute("data-front-right-left"),"true");assert.equal(await host.getAttribute("data-body-surface"),"translucent");assert.equal(await host.getAttribute("data-layers"),"body,skeleton,landmarks,leads");assert.match(await page.locator(".lead-3d-side-left").innerText(),/PATIENT RIGHT/);assert.match(await page.locator(".lead-3d-side-right").innerText(),/PATIENT LEFT/);
assert.equal(await page.locator("#leadCurrentInfo h3").textContent(),"Orient the chest");const guided=[];for(let i=0;i<D.guided.length;i++){guided.push(await page.locator("#leadCurrentInfo h3").textContent());if(i<D.guided.length-1)await page.locator("#leadNextStep").click();}assert.deepEqual(guided,D.guided.map(step=>step.lead));assert(guided.indexOf("V4")<guided.indexOf("V3"));assert.equal(await host.getAttribute("data-highlight"),"v1,v2,v3,v4,v5,v6");await page.locator('[data-layer="muscle"]').check();assert((await host.getAttribute("data-layers")).includes("muscle"));await page.locator('[data-layer="skeleton"]').uncheck();assert(!(await host.getAttribute("data-layers")).includes("skeleton"));await page.locator("#leadBodySurface").selectOption("opaque");assert.equal(await host.getAttribute("data-body-surface"),"opaque");await page.screenshot({path:path.join(root,"review-lead-placement/desktop-guided.png"),fullPage:true});
await page.locator('[data-tab="explore"]').click();await page.waitForSelector('#lead3DHost[data-ready="true"]');await page.locator('[data-explore="v6"]').click();assert.equal(await page.locator("#leadDetailCard h3").innerText(),"V6");assert.match(await page.locator("#leadDetailCard").innerText(),/left midaxillary line/i);assert.match(await page.locator("#leadDetailCard").innerText(),/Transverse plane/i);await page.locator('[data-explore="lead-ii"]').click();assert.match(await page.locator("#leadDetailCard").innerText(),/RA\(−\) → LL\(\+\)/);assert.match(await page.locator("#leadDetailCard").innerText(),/Frontal plane/i);
await page.locator('[data-tab="cards"]').click();assert.match(await page.locator(".lead-progress").innerText(),/Card 1 of 18/);assert.equal(await page.locator("#leadCardFront").innerText(),"V1");assert(await page.locator(".lead-card-thumb").isVisible());await page.locator("#leadCardReverse").click();assert.match(await page.locator("#leadCardFront").innerText(),/right sternal border/i);await page.locator("#leadFlashcard").focus();await page.keyboard.press("Enter");assert(await page.locator("#leadFlashcard").evaluate(el=>el.classList.contains("is-flipped")));
await page.locator('[data-tab="quiz"]').click();await page.locator("#leadQuizStart").click();for(let i=0;i<D.quiz.length;i++){const prompt=await page.locator("#leadQuizPrompt").textContent(),q=D.quiz.find(item=>item.prompt===prompt);assert(q);if(q.type==="tap")await page.locator(`[data-map-marker="${q.target}"]`).click();else await page.locator(`[data-quiz-opt="${q.answer}"]`).click();assert.match(await page.locator("#leadQuizFeedback").innerText(),/Correct/i);await page.locator("#leadQuizNext").click();}assert.match(await page.locator("#leadQuizPanel").innerText(),/Quiz results/i);
await page.locator('[data-tab="guided"]').click();await page.waitForSelector('#lead3DHost[data-ready="true"]');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator(".lead-3d-canvas").evaluate(el=>getComputedStyle(el).touchAction),"pan-y");await page.locator("#leadTouchToggle").click();assert.equal(await page.locator(".lead-3d-canvas").evaluate(el=>getComputedStyle(el).touchAction),"none");await page.locator("#leadTouchToggle").click();assert.equal(await page.locator(".lead-3d-canvas").evaluate(el=>getComputedStyle(el).touchAction),"pan-y");await page.emulateMedia({reducedMotion:"reduce"});await page.locator("#lead3DHost").scrollIntoViewIfNeeded();await page.waitForTimeout(250);await page.screenshot({path:path.join(root,"review-lead-placement/portrait-guided.png"),fullPage:true});await page.locator("#leadStudyBack").click();assert.equal(await page.locator(".lead-3d-canvas").count(),0);assert(await page.locator("#homeMenu").isVisible());assert.equal(requests.filter(url=>/^https?:/.test(url)).length,0);assert.deepEqual(errors,[]);
const fallback=await browser.newPage({viewport:{width:390,height:844}});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(/^webgl/.test(type))return null;return original.call(this,type,...args);};});await fallback.goto(pathToFileURL(path.join(root,"index.html")).href);await fallback.locator("#leadPlacementLaunch").click();await fallback.waitForFunction(()=>document.querySelector("#lead3DStatus")?.textContent.includes("3D unavailable"));assert(await fallback.locator("#lead2DFallback").isVisible());assert.equal(await fallback.locator("[data-map-marker]").count(),10);await fallback.screenshot({path:path.join(root,"review-lead-placement/webgl-fallback.png"),fullPage:true});await fallback.close();console.log("PASS: source facts, shared reversible cards, guided order, 3D layers, explore details, mixed quiz, portrait touch behavior, offline operation and WebGL fallback.");}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
