const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),vm=require('node:vm');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const ctx={};vm.runInNewContext(read('aspt/content.js')+';this.data=ASPT_DATA;',ctx);const D=JSON.parse(JSON.stringify(ctx.data));
assert.equal(read('index.html'),read('cmt-quiz.html'));assert.equal(D.terms.length,91);assert.equal(D.competencies.length,26);assert.equal(D.coverage.length,176);
const blueprint=JSON.parse(read('aspt/blueprint.json'));assert.deepEqual(D.terms.map(t=>({n:t.id,name:t.term,page:t.page})),blueprint.terms);
assert.deepEqual(D.competencies.map(c=>c.id),blueprint.competencies);
for(const l of D.lessons){for(const id of l.prerequisites)assert(D.lessons.some(x=>x.id===id));assert(l.body.length&&l.sources.length);}
for(const t of D.terms){assert(t.simple.length>10&&t.clinical.length>20);assert(D.coverage.some(r=>r.term===t.id||r.id==='T'+String(t.id).padStart(2,'0')));}
for(const v of Object.values(D.images)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,v.src))).digest('hex'),v.sha256);}
const scope=JSON.parse(read('aspt/scope-audit.json'));
assert.equal(scope.lessons.length,19);
for(const l of D.lessons){assert.equal(l.bodyRefs.length,l.body.length);for(const ref of l.bodyRefs)assert(ref.length>10);}
for(const row of scope.practice.excluded)assert(!D.lessons.some(l=>l.bank.includes(row.bankIndex)));
assert(!D.lessons.some(l=>l.visuals.includes('v012')||l.visuals.includes('v027')));
assert(!JSON.stringify(D.highYield).match(/cardiac output|ejection fraction|capnography|blood pH|60\/rate/i));
const server=http.createServer((req,res)=>{const target=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!target.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(target,(err,data)=>{if(err){res.writeHead(404);return res.end();}res.setHeader('Content-Type',target.endsWith('.js')?'text/javascript':target.endsWith('.css')?'text/css':target.endsWith('.jpg')?'image/jpeg':target.endsWith('.png')?'image/png':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,browser=await chromium.launch();
try{const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[],consoleErrors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!String(m.location().url||'').includes('/aspt/images/g03.png'))consoleErrors.push(m.text());});
for(const entry of ['index.html','cmt-quiz.html']){
 await page.goto(url+'/'+entry);await page.locator('#asptLaunch').click();assert(await page.locator('#asptHome').isVisible());
 assert((await page.locator('#asptContent').textContent()).includes('five recent mounted EKGs'));
 for(const l of D.lessons){await page.locator('.aspt-lesson-list [data-id="'+l.id+'"]').click();const text=await page.locator('#asptLesson').textContent();for(const label of ['ASPT EXAM REQUIREMENT','PREREQUISITE / FOUNDATION','ADDITIONAL EXPLANATION FROM CLASS SLIDES'])assert(text.includes(label));if(l.gap)assert(text.includes('ASP T GUIDE TOPIC NEEDING ADDITIONAL EXPLANATION'));}
 await page.locator('#asptHome nav [data-id="terms"]').click();assert.equal(await page.locator('.aspt-term').count(),91);await page.locator('#asptTermSearch').fill('ECTOPIC FIRING');assert.equal(await page.locator('.aspt-term').count(),1);assert((await page.locator('.aspt-term h4').textContent()).startsWith('56.'));
 await page.locator('#asptHome nav [data-id="coverage"]').click();assert.equal(await page.locator('.aspt-audit-row').count(),176);
 for(const status of ['Covered completely','Covered but needs reinforcement','Missing from class materials']){await page.locator('#asptAuditStatus').selectOption(status);assert.equal(await page.locator('.aspt-audit-row').count(),D.coverage.filter(r=>r.status===status).length);}
 await page.locator('#asptHome nav [data-id="exam-day"]').click();assert.equal(await page.locator('#asptContent article').count(),22);
 const result=await page.evaluate(()=>{let attempts=0;for(const q of ASPT.data.questions){for(let pick=0;pick<4;pick++){launch([q],'ASPT test');const cur=session.questions[0],choice=cur.opts.findIndex(o=>o.text===q.o[pick]);chooseAnswer(choice);if(session.score!==(pick===q.a?1:0))throw Error('score '+q._id);if(!document.querySelector('#qexplain').textContent.includes(q.e))throw Error('explanation '+q._id);chooseAnswer(choice);if(session.score!==(pick===q.a?1:0))throw Error('duplicate score');attempts++;}}return attempts;});assert.equal(result,96);
 const focusedChecks=await page.evaluate(()=>{let attempts=0;for(const l of ASPT.data.lessons){ASPT.practice(l.id);const qs=session.questions.map(q=>q.ref);for(const q of qs){if(q.studyLegacy?.includes('action-potential'))throw Error('advanced diagram leaked');for(let pick=0;pick<q.o.length;pick++){launch([q],'ASPT scope check');const cur=session.questions[0],choice=cur.opts.findIndex(o=>o.text===q.o[pick]);chooseAnswer(choice);if(session.score!==(pick===q.a?1:0))throw Error('focused score '+q._id);if(!document.querySelector('#qexplain').textContent.includes(q.e))throw Error('focused feedback '+q._id);attempts++;}}}return attempts;});assert(focusedChecks>700);
 const s19Checks=await page.evaluate(()=>{let attempts=0;for(const q of ASPT.data.section19Questions){for(let pick=0;pick<q.o.length;pick++){launch([q],'Section 19 exhaustive check');if(!document.querySelector('#qdiagram').classList.contains('hidden'))throw Error('Section 19 question requires a visual '+q.id);const cur=session.questions[0],choice=cur.opts.findIndex(o=>o.text===q.o[pick]);chooseAnswer(choice);if(session.score!==(pick===q.a?1:0))throw Error('Section 19 score '+q.id);const feedback=document.querySelector('#qexplain').textContent;if(!feedback.includes(q.e))throw Error('Section 19 explanation '+q.id);if(pick!==q.a&&!feedback.includes(q.wrong[pick]))throw Error('Section 19 distinction '+q.id+' option '+pick);attempts++;}}return attempts;});assert.equal(s19Checks,208);
 const mix=await page.evaluate(()=>{const normalUnion=new Set(),hardUnion=new Set(),answerPositions=new Set(),first=ASPT.data.section19Questions[0];let normalCategories=0,hardCategories=0;for(let i=0;i<20;i++){ASPT.practice('rhythms');if(session.questions.length!==24)throw Error('normal length');if(session.questions.some(x=>x.ref.d||x.ref.img||x.ref.dimg||x.ref.diagramId))throw Error('normal visual dependency');const ids=session.questions.map(x=>x.ref.id);if(new Set(ids).size!==ids.length)throw Error('normal duplicate');const groups=session.questions.map(x=>x.ref.attemptGroup).filter(Boolean);if(new Set(groups).size!==groups.length)throw Error('normal concept-family duplicate');session.questions.forEach(x=>normalUnion.add(x.ref.id));normalCategories=Math.max(normalCategories,new Set(session.questions.map(x=>x.ref.category)).size);ASPT.practice('rhythms',true);if(session.questions.length!==24)throw Error('hard length');if(session.questions.some(x=>x.ref.level<3))throw Error('hard level');if(session.questions.some(x=>x.ref.d||x.ref.img||x.ref.dimg||x.ref.diagramId))throw Error('hard visual dependency');const hardIds=session.questions.map(x=>x.ref.id);if(new Set(hardIds).size!==hardIds.length)throw Error('hard duplicate');const hardGroups=session.questions.map(x=>x.ref.attemptGroup).filter(Boolean);if(new Set(hardGroups).size!==hardGroups.length)throw Error('hard concept-family duplicate');session.questions.forEach(x=>hardUnion.add(x.ref.id));hardCategories=Math.max(hardCategories,new Set(session.questions.map(x=>x.ref.category)).size);launch([first],'answer shuffle');answerPositions.add(session.questions[0].answer);}return {normalUnion:normalUnion.size,hardUnion:hardUnion.size,normalCategories,hardCategories,answerPositions:answerPositions.size};});assert(mix.normalUnion>24);assert(mix.hardUnion>24);assert(mix.normalCategories>=14);assert(mix.hardCategories>=12);assert(mix.answerPositions>1);
 await page.evaluate(()=>ASPT.open());await page.locator('#asptHome nav [data-id="practice"]').click();await page.locator('#asptContent [data-action="practice"][data-id="all"]').click();assert.equal(await page.evaluate(()=>session.questions.length),24);assert(await page.locator('#quiz .aspt-return').isVisible());await page.locator('#quiz .aspt-return').click();assert(await page.locator('#asptHome').isVisible());
 await page.evaluate(()=>ASPT.practice('placement'));assert(await page.locator('#quiz').isVisible());await page.evaluate(()=>{session.questions.forEach((q,i)=>{session.idx=i;renderQuestion();chooseAnswer(q.answer);});showResults();});assert(await page.locator('#results .aspt-return').isVisible());await page.locator('#results .aspt-return').click();
 await page.locator('#asptHome [data-action="home"]').click();assert(await page.locator('#homeMenu').isVisible());assert(!(await page.locator('#asptHome').isVisible()));
}
await page.evaluate(()=>ASPT.open());await page.locator('#asptHome nav [data-id="diagrams"]').click();
for(const id of Object.keys(D.images)){const img=page.locator('#asptContent [data-action="zoom"][data-id="'+id+'"] img');await img.scrollIntoViewIfNeeded();await img.evaluate(img=>img.decode());assert.equal(await img.evaluate(i=>i.naturalWidth),D.images[id].width);}
for(const width of [390,768,1280]){
 await page.setViewportSize({width,height:900});await page.evaluate(()=>ASPT.open());await page.locator('#asptHome nav [data-id="path"]').click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'page overflow '+width);
 if(width===390)console.log('ASPT_SCREENSHOT_390='+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'));
 await page.locator('.aspt-lesson-list [data-id="rhythms"]').click();assert.equal(await page.locator('.s19-card').count(),D.section19Flashcards.length);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Section 19 overflow '+width);
 await page.locator('.aspt-lesson-list [data-id="waves"]').click();await page.locator('#asptLesson [data-action="zoom"][data-id="g03"]').click();assert(await page.locator('dialog').isVisible());await page.keyboard.press('Escape');await page.locator('.aspt-zoom').waitFor({state:'detached'});
}
await page.goto(url);await page.route('**/aspt/images/g03.png',r=>r.abort());await page.evaluate(()=>ASPT.open());await page.locator('.aspt-lesson-list [data-id="waves"]').click();await page.locator('#asptLesson [data-id="g03"]').scrollIntoViewIfNeeded();await page.locator('.aspt-image-error [data-action="retry"]').waitFor({state:'visible'});await page.unroute('**/aspt/images/g03.png');await page.locator('.aspt-image-error [data-action="retry"]').click();await page.waitForFunction(()=>document.querySelector('#asptLesson [data-id="g03"] img').naturalWidth>0);
assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);console.log('PASS 91 exact guide terms, 26 competencies, 176 checklist rows, 19 lessons, 52 text-only Section 19 questions / 208 answer paths, hard-mode balance, answer randomization, 6 source image hashes/dimensions, navigation/results, responsive layout, keyboard zoom, and clean console.');
}finally{await browser.close();}})().then(()=>server.close()).catch(e=>{console.error(e);server.close();process.exitCode=1;});
