/* ASPT-specific study layer; existing quiz and scoring engine retained. No persistent storage. */
const ASPT = (() => {
  const D=ASPT_DATA, root=document.createElement('section');
  const s19Svg=(label,path,extras='')=>`<svg class="s19-wave" viewBox="0 0 640 180" role="img" aria-label="${label}. Schematic teaching diagram, not a clinical tracing." xmlns="http://www.w3.org/2000/svg"><defs><pattern id="s19grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#f2cbd1" stroke-width="1"/></pattern></defs><rect width="640" height="180" rx="10" fill="#fff"/><rect width="640" height="150" fill="url(#s19grid)"/><line x1="18" y1="82" x2="622" y2="82" stroke="#94a3b8" stroke-width="1.5"/><path d="${path}" fill="none" stroke="#111827" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${extras}<text x="320" y="169" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#475569">SCHEMATIC TEACHING DIAGRAM · NOT A CLINICAL TRACING</text></svg>`;
  const s19P=(label,path)=>s19Svg(label,path,'<text x="30" y="74" font-family="system-ui,sans-serif" font-size="12" fill="#64748b">isoelectric baseline</text>');
  Object.assign(DIAGRAMS,{
    s19_rr_irregular:s19Svg('Unequal R-R spacing','M20 82 L65 82 L72 76 L78 82 L92 82 L100 42 L108 120 L116 82 L210 82 L218 76 L224 82 L238 82 L246 42 L254 120 L262 82 L325 82 L333 76 L339 82 L353 82 L361 42 L369 120 L377 82 L520 82 L528 76 L534 82 L548 82 L556 42 L564 120 L572 82 L620 82','<g font-family="system-ui,sans-serif" font-size="12" fill="#2563eb"><text x="98" y="28">R</text><text x="244" y="28">R</text><text x="359" y="28">R</text><text x="554" y="28">R</text></g>'),
    s19_rr_regular:s19Svg('Equal R-R spacing','M20 82 L65 82 L72 76 L78 82 L92 82 L100 42 L108 120 L116 82 L215 82 L222 76 L228 82 L242 82 L250 42 L258 120 L266 82 L365 82 L372 76 L378 82 L392 82 L400 42 L408 120 L416 82 L515 82 L522 76 L528 82 L542 82 L550 42 L558 120 L566 82 L620 82','<g font-family="system-ui,sans-serif" font-size="12" fill="#2563eb"><text x="98" y="28">R</text><text x="248" y="28">R</text><text x="398" y="28">R</text><text x="548" y="28">R</text></g>'),
    s19_p_diphasic:s19P('Diphasic P wave','M40 82 L220 82 C250 82 262 48 292 58 C315 66 324 82 338 82 C354 82 365 110 392 108 C420 106 430 82 458 82 L600 82'),
    s19_p_notched:s19P('Notched P wave','M40 82 L210 82 C240 82 250 48 285 50 C310 52 315 65 328 65 C343 65 350 48 380 50 C414 52 423 82 452 82 L600 82'),
    s19_p_peaked:s19P('Peaked P wave','M40 82 L248 82 C270 82 300 23 320 23 C340 23 370 82 392 82 L600 82'),
    s19_p_flattened:s19P('Flattened P wave','M40 82 L215 82 C255 82 270 70 320 70 C370 70 385 82 425 82 L600 82'),
    s19_af_strip:s19Svg('Fibrillatory baseline with irregular QRS spacing','M18 84 L28 77 L38 88 L48 79 L58 86 L68 75 L76 84 L84 42 L92 120 L100 83 L111 78 L121 89 L131 76 L141 86 L151 79 L161 88 L171 77 L181 85 L191 78 L201 82 L211 40 L219 121 L227 84 L237 76 L247 89 L257 78 L267 86 L277 75 L287 88 L297 79 L307 85 L317 76 L327 84 L337 41 L345 120 L353 82 L363 76 L373 89 L383 77 L393 86 L403 75 L413 88 L423 78 L433 85 L443 77 L453 88 L463 76 L473 85 L483 79 L493 88 L503 77 L513 84 L523 40 L531 121 L539 83 L549 76 L559 88 L569 78 L579 86 L589 77 L599 88 L620 82'),
    s19_flutter_strip:s19Svg('Organized sawtooth flutter activity','M18 82 L36 66 L54 82 L72 66 L90 82 L108 66 L126 82 L144 66 L162 82 L176 82 L184 40 L192 120 L200 82 L218 66 L236 82 L254 66 L272 82 L290 66 L308 82 L326 66 L344 82 L362 66 L380 82 L394 82 L402 40 L410 120 L418 82 L436 66 L454 82 L472 66 L490 82 L508 66 L526 82 L544 66 L562 82 L580 66 L598 82 L620 82'),
    s19_junctional_strip:s19Svg('Inverted P waves before narrow QRS complexes','M18 82 L70 82 C78 82 82 98 92 98 C102 98 106 82 114 82 L132 82 L140 42 L148 120 L156 82 L270 82 C278 82 282 98 292 98 C302 98 306 82 314 82 L332 82 L340 42 L348 120 L356 82 L470 82 C478 82 482 98 492 98 C502 98 506 82 514 82 L532 82 L540 42 L548 120 L556 82 L620 82'),
    s19_ventricular_strip:s19Svg('Premature wide bizarre ventricular complex','M18 82 L70 82 C82 82 88 68 100 68 C112 68 118 82 130 82 L148 82 L156 42 L164 120 L172 82 L280 82 C292 82 298 68 310 68 C322 68 328 82 340 82 L356 82 L366 40 L386 122 L420 46 L448 112 L468 82 L620 82'),
    s19_asystole_strip:s19Svg('Nearly flat trace without QRS complexes','M18 82 L160 82 L220 81 L300 82 L380 82 L460 83 L520 82 L620 82'),
    s19_paced_strip:s19Svg('Pacing spike before captured complex','M18 82 L100 82 L108 20 L112 82 L128 82 L136 42 L144 120 L152 82 L292 82 L300 20 L304 82 L320 82 L328 42 L336 120 L344 82 L484 82 L492 20 L496 82 L512 82 L520 42 L528 120 L536 82 L620 82'),
    s19_wandering_p:s19Svg('Changing P-wave morphology before conducted QRS complexes','M18 82 L52 82 C62 82 68 68 78 68 C88 68 94 82 104 82 L122 82 L130 42 L138 120 L146 82 L238 82 C248 82 252 62 264 64 C274 65 280 74 286 74 C292 74 298 64 310 64 C322 64 328 82 338 82 L356 82 L364 42 L372 120 L380 82 L472 82 C480 82 484 98 494 98 C504 98 510 82 518 82 L536 82 L544 42 L552 120 L560 82 L620 82')
  });
  root.id='asptHome'; root.className='hidden aspt';
  document.getElementById('home').appendChild(root);
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lesson=id=>D.lessons.find(l=>l.id===id);
  const source=s=>s.map(([c,p])=>'Chapter '+String(c).padStart(2,'0')+', pp. '+p).join('; ');
  const button=(label,action,id='')=>'<button type="button" data-action="'+action+'"'+(id?' data-id="'+escape(id)+'"':'')+'>'+escape(label)+'</button>';
  const linkLesson=id=>lesson(id)?button(lesson(id).title,'lesson',id):button('Exam-Day Requirements','tab','exam-day');
  function section19Panel(){
    const cards=(D.section19Flashcards||[]).map((card,i)=>'<details class="s19-card"><summary><span>Card '+(i+1)+'</span>'+escape(card.front)+'</summary><p>'+escape(card.back)+'</p><small>'+escape(card.sourceRefs.join(' · '))+'</small></details>').join('');
    return '<section class="s19-panel" aria-labelledby="s19PracticeTitle"><p class="aspt-kicker">Section 19 exam practice</p><h4 id="s19PracticeTitle">Rhythm discrimination bank</h4><p>Normal attempts draw 24 balanced questions, primarily Levels 2–4. Answer order and safe wording variants are randomized.</p><div class="aspt-links">'+button('Start Section 19 test','practice','rhythms')+button('🔥 HARD MODE','practice-hard','rhythms')+button('Open source ECG trainer','ecg')+'</div><details class="s19-deck"><summary>Study '+D.section19Flashcards.length+' Section 19 comparison flashcards</summary><div class="s19-card-grid">'+cards+'</div></details></section>';
  }
  let tab='path', current='foundation', fromExam=false;
  const returns=['quiz','results'].map(id=>{
    const b=document.createElement('button'); b.type='button';b.className='btn secondary hidden aspt-return';
    b.textContent='← Return to ASPT exam study';b.onclick=()=>open();document.getElementById(id).prepend(b);return b;
  });
  const oldHome=goHome;
  goHome=function(){oldHome();root.classList.add('hidden');document.getElementById('home').classList.remove('aspt-active');fromExam=false;returns.forEach(b=>b.classList.add('hidden'));};
  const homeButton=document.createElement('button');homeButton.className='btn';homeButton.type='button';
  homeButton.id='asptLaunch';homeButton.textContent='ASPT National EKG Exam';
  const sm=document.createElement('small');sm.textContent='September 22 • guide checklist, 91 terms, illustrated lessons and exam-focused practice';homeButton.appendChild(sm);
  homeButton.onclick=()=>open();document.getElementById('homeMenu').insertBefore(homeButton,document.getElementById('homeMenu').children[1]);

  function open(){goHome();if(typeof khHideAll==='function')khHideAll();hide('homeMenu');show('home');show('asptHome');document.getElementById('home').classList.add('aspt-active');render();window.scrollTo(0,0);}
  function figure(id){
    const v=D.images[id]||StudyTeaching.visuals[id];if(!v)return '';
    const citation=v.source||('Chapter '+v.chapter+', page '+v.page);
    return '<figure><button class="aspt-image-button" type="button" data-action="zoom" data-id="'+escape(id)+'" aria-label="Enlarge '+escape(v.title)+'"><img loading="lazy" src="'+escape(v.src)+'" alt="'+escape(v.title)+'" width="'+v.width+'" height="'+v.height+'"></button><figcaption><strong>'+escape(citation)+'</strong><br>'+escape(D.visualCues?.[id]||v.cue)+'<br><small>Select the image to enlarge.</small></figcaption></figure>';
  }
  function adminBox(){return '<aside class="aspt-notice"><h3>Exam-Day Requirements</h3><p><strong>Multiple choice • one correct answer • 90 minutes maximum • 80% to pass</strong></p><p>Bring the supervisor/instructor letter documenting qualification and <strong>five recent mounted EKGs</strong>. Include <strong>one mounted, signed EKG in the test packet</strong>. The guide says the test will not be graded if these requirements are not met.</p><p>Page 3 is less specific than page 2 about the five-count. Confirm the packet with your instructor before September 22. Interpretation on the submitted tracing is optional.</p><small>ASPT guide, pp. 2–3 · January 2026 revision</small><p>'+button('Read all exam-day and certification instructions','tab','exam-day')+'</p></aside>';}
  function lessonView(l){
    const extraKeys=l.id==='anatomy'?['anatomy','ventricle','orientation']:l.id==='placement'?['placement']:[];
    return '<article><p class="aspt-kicker">'+escape(l.domain||'Exam study')+'</p><h3>'+escape(l.title)+'</h3><div class="aspt-requirement"><strong>ASPT EXAM REQUIREMENT</strong><p>'+escape(l.requirement)+'</p><small>Guide pp. '+l.guide.join(', ')+'</small></div><div class="aspt-foundation"><h4>PREREQUISITE / FOUNDATION</h4>'+(l.prerequisites.length?'<p>Review these concepts first:</p><div class="aspt-links">'+l.prerequisites.map(linkLesson).join('')+'</div>':'<p>This is a starting foundation. Learn these basic relationships before the later lessons.</p>')+'</div><h4>ADDITIONAL EXPLANATION FROM CLASS SLIDES</h4><p class="aspt-source">'+escape(source(l.sources))+'</p>'+l.body.map((p,i)=>'<p>'+escape(p)+'</p><p class="aspt-source aspt-point-source">'+escape(l.bodyRefs[i])+'</p>').join('')+(extraKeys.length?'<p class="aspt-source">References for required guide labels/placement only: '+extraKeys.map(k=>'<a href="'+D.extras[k].url+'" target="_blank" rel="noopener">'+escape(D.extras[k].title)+'</a>').join(' · ')+'</p>':'')+(l.gap?'<aside class="aspt-gap"><strong>ASP T GUIDE TOPIC NEEDING ADDITIONAL EXPLANATION</strong><p>'+escape(l.gap)+'</p></aside>':'')+(l.visuals||[]).map(figure).join('')+(l.id==='anatomy'?heartTable():'')+(l.id==='rhythms'?section19Panel():'<div class="aspt-links">'+button('Practice this topic','practice',l.id)+'</div>')+'</article>';
  }
  function heartTable(){return '<h4>All labels on the guide heart diagram</h4><p>For each label: locate it, state its function, then name the next structure in the blood-flow route when applicable. Compare paired chambers, valves and septa.</p><dl>'+D.heartLabels.map(([name,meaning,missing])=>'<div><dt>'+escape(name)+'</dt><dd>'+escape(meaning)+(missing?' <strong>Supplemental anatomy explanation; missing from class text.</strong>':'')+'</dd></div>').join('')+'</dl>';}
  function render(){
    root.innerHTML='<header><p class="aspt-kicker">Your September 22, 2026 exam</p><h2>ASPT National EKG Exam</h2><p>The 2026 ASPT guide sets the scope. Explanations stay at the basic class level, with source pages beside each point. These are practice resources, not official exam questions.</p>'+button('← All study modes','home')+'</header><nav aria-label="ASPT study sections">'+[['path','Study path'],['terms','91 terms'],['diagrams','Diagram lab'],['coverage','Coverage checklist'],['review','Final review'],['practice','Practice'],['exam-day','Exam-Day Requirements']].map(([id,n])=>'<button type="button" data-action="tab" data-id="'+id+'" aria-pressed="'+(tab===id)+'">'+n+'</button>').join('')+'</nav><div id="asptContent"></div>';
    const box=root.querySelector('#asptContent');
    if(tab==='path')box.innerHTML=adminBox()+'<h3>Study path</h3><p>'+escape(D.scopeNote)+'</p><p>Start with foundations, then follow the guide domains. Each lesson separates the requirement, prerequisite links and class explanation.</p><div class="aspt-layout"><div class="aspt-lesson-list">'+D.lessons.map((l,i)=>'<button type="button" data-action="lesson" data-id="'+l.id+'" aria-pressed="'+(current===l.id)+'">'+(i+1)+'. '+escape(l.title)+'</button>').join('')+'</div><div id="asptLesson">'+lessonView(lesson(current))+'</div></div>';
    if(tab==='terms'){box.innerHTML='<h3>Terminology Used on National Testing</h3><p>All 91 numbered entries are retained, including duplicates and the guide’s unusual spellings. Start with the plain-language meaning, then use the distinction to reason through choices.</p><label>Search terms <input id="asptTermSearch" type="search" placeholder="Term, definition or number"></label><p id="asptTermCount" role="status"></p><div id="asptTerms"></div>';terms('');}
    if(tab==='coverage'){box.innerHTML='<h3>ASPT coverage audit</h3><p>These statuses describe source coverage, not your mastery or a guaranteed exam result. “Missing from class materials” items remain included from the ASPT guide or a clearly labeled supplement. Administrative requirements are absent from academic slides but fully listed here.</p><label>Search checklist <input id="asptAuditSearch" type="search"></label><label>Status <select id="asptAuditStatus"><option>All statuses</option><option>Covered completely</option><option>Covered but needs reinforcement</option><option>Missing from class materials</option></select></label><p id="asptAuditCount" role="status"></p><div id="asptAudit"></div><details><summary>Source inventory: all 13 slideshows</summary><ul>'+D.chapters.map(c=>'<li>'+escape(c.file)+' — '+c.pages+' pages reviewed</li>').join('')+'</ul><p>Chapter 12 supplies practice tracings; unreviewed examples are not promoted as verified strips. Chapter 13 summarizes the course. The guide supplies the specific exam scope, not the relative length of a slideshow.</p></details>';audit();}
    if(tab==='diagrams')box.innerHTML='<h3>Diagram lab</h3><p>Cover a label, identify the structure or wave, explain its function, and answer “what happens next?” Open the related lesson for the complete explanation.</p>'+Object.entries(D.images).map(([id,v])=>'<article><h4>'+escape(v.title)+'</h4>'+figure(id)+linkLesson(v.lesson)+(id==='g01'?heartTable():'')+'</article>').join('')+'<h4>More class illustrations</h4><p>The lessons include the class conduction map, blood flow, respiratory pathway and anatomical landmarks, with prompts explaining what to identify.</p>'+linkLesson('conduction')+linkLesson('circulation')+linkLesson('airway');
    if(tab==='review')box.innerHTML='<h3>Final high-yield exam review</h3><p>Guide scope with class reference values. Apply values only when the recording settings and visible evidence support them.</p>'+D.highYield.map(g=>'<article><h4>'+escape(g.title)+'</h4><ul>'+g.items.map(s=>'<li>'+escape(s)+'</li>').join('')+'</ul></article>').join('')+button('Practice the exam focus set','practice','all');
    if(tab==='practice')box.innerHTML='<h3>Exam-focused practice</h3><p>Use the existing quiz engine with immediate scoring and explanations after every answer. The 24-question focus set covers placements, measurements, guide-wave identification and exam requirements. Section 19 uses its own balanced, tiered rhythm bank; practice length does not represent an official exam question count.</p>'+button('Start 24-question focus set','practice','all')+'<section class="s19-panel"><h4>Section 19 · ECG Rhythms</h4><p>Normal mode is primarily Levels 2–4. Hard Mode favors Levels 3–4 and increases schematic waveform/rhythm-strip interpretation.</p><div class="aspt-links">'+button('Start Section 19 test','practice','rhythms')+button('🔥 HARD MODE','practice-hard','rhythms')+'</div></section><div class="aspt-lesson-list">'+D.lessons.filter(l=>l.id!=='rhythms').map(l=>button(l.title,'practice',l.id)).join('')+'</div>'+button('Source ECG strip trainer','ecg');
    if(tab==='exam-day')box.innerHTML=adminBox()+'<h3>Complete guide instructions</h3>'+D.admin.map(a=>'<article><h4>'+escape(a.title)+'</h4><p>'+escape(a.text)+'</p><small>ASPT guide, page '+a.page+'</small></article>').join('');
  }
  function terms(query){const rows=D.terms.filter(t=>(t.id+' '+t.term+' '+t.simple+' '+t.clinical).toLowerCase().includes(query.toLowerCase()));root.querySelector('#asptTermCount').textContent=rows.length+' of 91 terms';root.querySelector('#asptTerms').innerHTML=rows.map(t=>'<article class="aspt-term"><h4>'+t.id+'. '+escape(t.term)+'</h4><strong>In simple language</strong><p>'+escape(t.simple)+'</p><strong>For multiple-choice questions</strong><p>'+escape(t.clinical)+'</p><small>ASPT EXAM REQUIREMENT · guide p. '+t.page+' · '+escape(t.status)+'</small><p class="aspt-source">Class explanation: '+escape(source(t.sources))+'</p>'+linkLesson(t.lesson)+'</article>').join('');}
  function audit(){const q=root.querySelector('#asptAuditSearch').value.toLowerCase(),status=root.querySelector('#asptAuditStatus').value;const rows=D.coverage.filter(r=>(status==='All statuses'||r.status===status)&&(r.id+' '+r.label+' '+r.group+' '+r.note).toLowerCase().includes(q));root.querySelector('#asptAuditCount').textContent=rows.length+' of '+D.coverage.length+' checklist items';root.querySelector('#asptAudit').innerHTML=rows.map(r=>'<article class="aspt-audit-row"><strong>'+escape(r.id+' · '+r.label)+'</strong><p class="aspt-status">'+escape(r.status)+'</p><p>'+escape(r.note)+'</p><small>'+escape(r.group)+' · ASPT guide p. '+r.page+'</small><div>'+linkLesson(r.lesson)+(r.also||[]).map(linkLesson).join('')+'</div></article>').join('');}
  function section19Pick(hard=false){
    const limit=24, used=new Set(), picked=[];
    const pool=shuffle((D.section19Questions||[]).filter(q=>!hard||q.level>=3).map(q=>({...q})));
    const take=q=>{if(!q||used.has(q.id)||picked.length>=limit)return false;used.add(q.id);picked.push(q);return true;};
    if(hard){
      const visuals=shuffle(pool.filter(q=>q.d));
      for(const q of visuals){if(picked.filter(x=>x.d).length>=10)break;take(q);}
    }
    const categories=shuffle([...new Set(pool.map(q=>q.category))]);
    while(picked.length<limit){
      let moved=false;
      for(const category of shuffle(categories.slice())){
        const q=pool.find(x=>x.category===category&&!used.has(x.id));
        if(take(q))moved=true;
        if(picked.length>=limit)break;
      }
      if(!moved)break;
    }
    for(const q of pool){if(picked.length>=limit)break;take(q);}
    return shuffle(picked).map(q=>{
      const wordings=[q.q,...(q.variants||[])];
      return {...q,_id:q.id,asptFocused:true,q:wordings[Math.floor(Math.random()*wordings.length)]};
    });
  }
  function practice(id,hard=false){const l=lesson(id);const qs=id==='all'?D.questions.slice():id==='rhythms'?section19Pick(hard):[...D.questions.filter(q=>q.lesson===id),...(l?.bank||[]).map(i=>{const q=BANK[i];return q&&{...q,_id:'aspt-class-'+i,asptFocused:true,e:D.practiceExplanations?.[i]||q.e,studyCue:D.visualCues?.[q.studyRef],...D.practiceOverrides?.[i]};}).filter(q=>q&&q.o)];if(!qs.length)return;hide('asptHome');fromExam=true;returns.forEach(b=>b.classList.remove('hidden'));launch(shuffle(qs.slice()),'ASPT · '+(l?l.title:'Exam focus')+(hard?' · HARD MODE':''));}
  function zoom(id){const v=D.images[id]||StudyTeaching.visuals[id];ImageViewer.open(v.src,v.title,{id:'aspt-image-dialog',className:'aspt-zoom'});}
  root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.id;switch(b.dataset.action){case'home':goHome();break;case'tab':tab=id;render();break;case'lesson':tab='path';current=id;render();root.querySelector('#asptLesson').scrollIntoView({block:'start'});break;case'practice':practice(id);break;case'practice-hard':practice(id,true);break;case'zoom':zoom(id);break;case'retry':{const f=b.closest('figure'),im=f.querySelector('img');b.parentElement.remove();im.src=im.getAttribute('src');break;}case'ecg':goHome();showEcg();break;}});
  root.addEventListener('error',e=>{if(e.target.tagName!=='IMG')return;const f=e.target.closest('figure');if(!f||f.querySelector('.aspt-image-error'))return;const msg=document.createElement('div');msg.className='aspt-image-error';msg.setAttribute('role','status');msg.innerHTML='<p>Image could not load. The source and explanation remain below.</p>'+button('Retry image','retry');f.appendChild(msg);},true);
  root.addEventListener('input',e=>{if(e.target.id==='asptTermSearch')terms(e.target.value);if(e.target.id==='asptAuditSearch')audit();});
  root.addEventListener('change',e=>{if(e.target.id==='asptAuditStatus')audit();});
  return {open,practice,data:D};
})();
