/* Lead Placement Lab. Isolated runtime injection; no changes to global quiz scoring. */
"use strict";
const LeadPlacementLab = (() => {
  const D=typeof LEAD_PLACEMENT!=="undefined"?LEAD_PLACEMENT:null;
  const home=document.getElementById("home"),menu=document.getElementById("homeMenu");
  if(!D||!home||!menu){console.warn("Lead Placement Lab did not initialize.");return null;}
  const root=document.createElement("section");root.id="leadPlacementHome";root.className="hidden lead-study";root.setAttribute("aria-labelledby","leadStudyTitle");home.append(root);
  const moduleBase=new URL(".",document.currentScript.src).href;
  const escape=(value)=>String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const shuffle=(items)=>{const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  const state={tab:"guided",step:0,selected:"v1",layers:{body:true,skeleton:true,muscle:false,landmarks:true,leads:true},bodySurface:"translucent",touch:false,card:0,cardOrder:D.cards.map((_,i)=>i),cardReverse:false,cardFlipped:false,quizOrder:[],quiz:0,quizPicked:null,quizTapCorrect:null,quizTapPoint:null,quizScore:0,quizDone:false};
  let view=null,viewGeneration=0,assetPromise=null,use3D=true;

  const launch=document.createElement("button");launch.className="btn secondary";launch.type="button";launch.id="leadPlacementLaunch";launch.append(document.createTextNode("📍 Lead Placement Lab"));const sub=document.createElement("small");sub.textContent=D.subtitle;launch.append(sub);launch.addEventListener("click",open);
  const rhythmButton=Array.from(menu.querySelectorAll("button")).find((button)=>/ECG Rhythm Practice/.test(button.textContent||""));menu.insertBefore(launch,rhythmButton||null);
  const oldHome=goHome;goHome=function(){releaseView();root.classList.add("hidden");home.classList.remove("lead-study-active");oldHome();};
  document.addEventListener("visibilitychange",()=>{if(!document.hidden)view?.draw?.();});

  function scriptFile(path){return new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=moduleBase+path;script.onload=resolve;script.onerror=()=>{script.remove();reject(new Error("Lead-placement asset unavailable"));};document.head.append(script);});}
  function loadAssets(){if(!assetPromise)assetPromise=(async()=>{if(!window.EcgThree)await scriptFile("../ecg-study/vendor/three-gltf.min.js");if(!window.LeadTorsoModelData)await scriptFile("assets/torso-model-data.js");if(!window.LeadTorso3D)await scriptFile("torso-3d.js");})().catch((error)=>{assetPromise=null;throw error;});return assetPromise;}
  function releaseView(){viewGeneration++;view?.dispose?.();view=null;}
  function open(){goHome();if(typeof khHideAll==="function")khHideAll();hide("homeMenu");show("home");show("leadPlacementHome");home.classList.add("lead-study-active");renderAll();window.scrollTo(0,0);root.querySelector("#leadStudyTitle")?.focus();}

  function leadById(id){return D.leads.find((item)=>item.id===id)||D.limbViews.find((item)=>item.id===id)||D.landmarks.find((item)=>item.id===id);}
  function leadAnchor(id){return D.leads.find((item)=>item.id===id)?.anchor||null;}
  function allExploreItems(){return [...D.leads,...D.limbViews,...D.landmarks];}
  function highlights(){return state.tab==="guided"?D.guided[state.step].highlights:[state.selected];}
  function layerControls(quizMode=false){return `<fieldset class="lead-layer-controls"><legend>Layers</legend><label>Body <select id="leadBodySurface" aria-label="Body surface visibility"><option value="opaque" ${state.bodySurface==="opaque"?"selected":""}>Opaque</option><option value="translucent" ${state.bodySurface==="translucent"?"selected":""}>Translucent</option><option value="hidden" ${state.bodySurface==="hidden"?"selected":""}>Hidden</option></select></label>${[["skeleton","Skeleton"],["muscle","Muscles"],["landmarks","Landmarks"],["leads","Leads"]].map(([id,label])=>`<label><input type="checkbox" data-layer="${id}" ${state.layers[id]&&!(quizMode&&id==="leads")?"checked":""} ${quizMode&&id==="leads"?"disabled aria-describedby=\"leadQuizMarkerNote\"":""}> ${label}</label>`).join("")}</fieldset>`;}
  function viewControls(){return `<div class="lead-view-controls" role="group" aria-label="3D view controls"><button type="button" data-view-preset="front">Front</button><button type="button" data-view-preset="left-oblique">Left oblique</button><button type="button" data-view-preset="right-oblique">Right oblique</button><button type="button" data-view-preset="reset">Reset</button><button type="button" id="leadZoomIn" aria-label="Zoom in">Zoom +</button><button type="button" id="leadZoomOut" aria-label="Zoom out">Zoom −</button><button type="button" id="leadTouchToggle" aria-pressed="${state.touch}">${state.touch?"Unlock page scrolling":"Enable touch rotation"}</button></div>`;}
  function placementFigure(classes="",buttons=true){
    const pos=Object.fromEntries(D.leads.filter((item)=>item.anchor?.fallbackPercent).map((item)=>[item.id,item.anchor.fallbackPercent]));
    const markers=buttons?Object.entries(pos).map(([id,[x,y]])=>`<button type="button" class="lead-map-marker" data-map-marker="${id}" style="left:${x}%;top:${y}%" aria-label="${id.toUpperCase()} location">${id.toUpperCase()}</button>`).join(""):"";
    return `<div class="lead-map ${classes}" role="${buttons?"group":"img"}" aria-label="Front-facing torso placement reference"><svg viewBox="0 0 300 380" aria-hidden="true"><path class="lead-map-body" d="M88 42 Q115 18 150 20 Q185 18 212 42 L260 82 Q245 118 224 126 L216 348 Q184 366 150 368 Q116 366 84 348 L76 126 Q55 118 40 82 Z"/><path class="lead-map-sternum" d="M150 78 L150 235"/><path class="lead-map-clavicle" d="M150 82 Q118 68 88 86 M150 82 Q182 68 212 86"/>${[112,139,166,193,220,247].map((y,i)=>`<path class="lead-map-rib" d="M150 ${y} Q${112-i*3} ${y-12} ${78-i*2} ${y+8} M150 ${y} Q${188+i*3} ${y-12} ${222+i*2} ${y+8}"/>`).join("")}<path class="lead-map-line" d="M188 75 L188 270 M222 90 L222 270 M248 106 L248 270"/><text x="188" y="292">MCL</text><text x="222" y="310">AAL</text><text x="248" y="328">MAL</text></svg>${markers}<span class="lead-map-side left">PATIENT RIGHT</span><span class="lead-map-side right">PATIENT LEFT</span></div>`;
  }
  function sequenceStrip(){return `<div class="lead-sequence" aria-label="Preferred chest lead placement sequence">${D.chestSequence.map((id,i)=>`<span data-seq="${id}" class="${highlights().includes(id)?"active":""}">${id.toUpperCase()}</span>${i<D.chestSequence.length-1?"<b aria-hidden=\"true\">→</b>":""}`).join("")}</div>`;}
  function viewer(quizMode=false){return `<div class="lead-view-shell${quizMode?" lead-quiz-view-shell":""}">${layerControls(quizMode)}${viewControls()}<p id="lead3DStatus" class="lead-status" role="status">${use3D?"Loading local 3D torso…":"Using the native 2D placement reference."}</p><div id="lead3DHost" class="lead-3d-host" hidden></div><div id="lead2DFallback" ${use3D?"hidden":""}>${placementFigure("lead-fallback-map")}</div><p class="lead-orientation"><strong>${escape(D.patient.note)}</strong> Return to Front after rotating when checking patient side.</p><p class="lead-help">${quizMode?'<span id="leadQuizMarkerNote">Lead labels are hidden during 3D placement questions. Tap the anatomical surface.</span> ':''}Mouse drag rotates. Touch scrolls by default; enable touch rotation for orbit and pinch, then unlock scrolling. RA/LA/RL/LL are external teaching labels with leader lines toward limb regions, not anatomical lead views.</p></div>`;}
  function guideCard(){const item=D.guided[state.step];return `<article class="lead-info-card" id="leadCurrentInfo"><p class="lead-step">Step ${state.step+1} of ${D.guided.length}</p><h3>${escape(item.lead)}</h3><dl><div><dt>Exact placement</dt><dd>${escape(item.placement)}</dd></div><div><dt>Memory cue</dt><dd>${escape(item.cue)}</dd></div></dl><div class="lead-step-controls"><button type="button" id="leadPrevStep">Previous</button><button type="button" id="leadNextStep">${state.step===D.guided.length-1?"Start again":"Next"}</button></div></article>`;}
  function guidedPanel(){return `<div id="leadGuidedPanel">${viewer()}${guideCard()}${sequenceStrip()}</div>`;}
  function detailCard(id=state.selected){const item=leadById(id)||leadById("v1");const isLandmark=D.landmarks.some((x)=>x.id===item.id);return `<article class="lead-info-card" id="leadDetailCard" aria-live="polite"><h3>${escape(item.name)}</h3><dl><div><dt>${isLandmark?"Definition":"Placement / direction"}</dt><dd>${escape(item.placement)}</dd></div>${item.landmark?`<div><dt>Landmark</dt><dd>${escape(item.landmark)}</dd></div>`:""}${item.plane?`<div><dt>Plane</dt><dd>${escape(item.plane)}</dd></div>`:""}${item.side?`<div><dt>Patient orientation</dt><dd>${escape(item.side)}</dd></div>`:""}<div><dt>Memory cue</dt><dd>${escape(item.mnemonic)}</dd></div></dl></article>`;}
  function explorePanel(){const groups=[["Chest leads",D.leads.filter((x)=>x.family==="chest")],["Limb electrodes",D.leads.filter((x)=>x.family==="limb")],["Limb lead views",D.limbViews],["Landmarks",D.landmarks]];return `<div id="leadExplorePanel">${viewer()}<div class="lead-explore-picker">${groups.map(([label,items])=>`<fieldset><legend>${label}</legend>${items.map((item)=>`<button type="button" data-explore="${item.id}" aria-pressed="${state.selected===item.id}">${escape(item.name)}</button>`).join("")}</fieldset>`).join("")}</div>${detailCard()}${sequenceStrip()}</div>`;}
  function thumb(id){const p=leadAnchor(id)?.fallbackPercent||[64,59];return `<svg class="lead-card-thumb" viewBox="0 0 180 150" role="img" aria-label="Front torso thumbnail highlighting ${escape(id.toUpperCase())}"><path d="M55 18 Q90 2 125 18 L156 44 L139 140 H41 L24 44 Z"/><path d="M90 28 L90 112 M90 32 Q68 25 50 38 M90 32 Q112 25 130 38"/><circle cx="${p[0]*1.8}" cy="${p[1]*1.5}" r="7"/><text x="${p[0]*1.8}" y="${p[1]*1.5+3}" text-anchor="middle">${escape(id.toUpperCase())}</text></svg>`;}
  function cardsPanel(){const index=state.cardOrder[state.card],card=D.cards[index],front=state.cardReverse?card.definition:card.term,back=state.cardReverse?card.term:card.definition;return `<div id="leadCardsPanel"><p class="lead-progress">Card ${state.card+1} of ${D.cards.length}</p><div class="lead-card-tools"><button type="button" id="leadCardReverse" aria-pressed="${state.cardReverse}">Show definitions first</button><button type="button" id="leadCardShuffle">Shuffle</button></div><div class="lead-flashcard${state.cardFlipped?" is-flipped":""}" id="leadFlashcard" role="button" tabindex="0" aria-pressed="${state.cardFlipped}" aria-label="Flashcard; activate to flip"><div class="lead-card-face lead-card-front"><small>${state.cardReverse?"Definition":"Term"}</small>${card.visual?thumb(card.visual):""}<strong id="leadCardFront">${escape(front)}</strong></div><div class="lead-card-face lead-card-back"><small>${state.cardReverse?"Term":"Definition"}</small><strong id="leadCardBack">${escape(back)}</strong></div></div><div class="lead-card-nav"><button type="button" id="leadCardPrev">Previous</button><button type="button" id="leadCardFlip">Flip</button><button type="button" id="leadCardNext">Next</button></div><p class="lead-help">Reverse mode swaps each fact instead of duplicating it. Chest-placement cards include a small front-view reference.</p></div>`;}

  function currentQuiz(){return D.quiz[state.quizOrder[state.quiz]];}
  function quizDiagram(){const answered=state.quizPicked!==null;return `<div class="lead-quiz-3d">${viewer(true)}${answered?`<div class="lead-tap-legend" aria-label="Tap result legend"><span class="learner">Your selection</span><span class="answer">Correct location</span></div>`:""}</div>`;}
  function quizPanel(){
    if(!state.quizOrder.length)return `<div id="leadQuizPanel"><p>Practice chest locations, landmarks, lead pairings, augmented directions and frontal versus transverse views. Feedback appears immediately.</p><button type="button" id="leadQuizStart" class="btn">Start quiz (${D.quiz.length} questions)</button></div>`;
    if(state.quizDone){const total=state.quizOrder.length,pct=Math.round(state.quizScore/total*100);return `<div id="leadQuizPanel"><h3>Quiz results</h3><div class="score-circle ${pct>=80?"pass":"fail"}"><span class="pct">${pct}%</span><span class="lbl">${state.quizScore} / ${total}</span></div><button type="button" id="leadQuizStart" class="btn">Retake quiz</button></div>`;}
    const q=currentQuiz(),answered=state.quizPicked!==null,isTap=q.type==="tap";let body="";
    if(isTap)body=quizDiagram(q);else{if(q.type==="identify"){const [x,y]=leadAnchor(q.highlight)?.fallbackPercent||[50,50];body=placementFigure("lead-identify-map",false).replace("</div>",`<span class="lead-identify-dot" data-highlight="${q.highlight}" style="left:${x}%;top:${y}%">${q.highlight.toUpperCase()}</span></div>`);}body+=`<div class="lead-quiz-options">${q.options.map((option,i)=>{let cls="";if(answered&&i===q.answer)cls="correct";else if(answered&&i===state.quizPicked)cls="wrong";return `<button type="button" data-quiz-opt="${i}" class="${cls}" ${answered?"disabled":""}>${escape(option)}</button>`;}).join("")}</div>`;}
    const correct=answered&&(isTap?state.quizTapCorrect:state.quizPicked===q.answer);const feedback=answered?`<div class="lead-feedback ${correct?"correct":"wrong"}" id="leadQuizFeedback" tabindex="-1"><strong>${correct?"Correct":"Not quite"}</strong><p>${escape(q.explain)}</p>${isTap&&!correct?`<p>Your selection is marked in red; the correct marker and landmark are shown in green.</p>`:""}</div><button type="button" id="leadQuizNext" class="btn">${state.quiz===state.quizOrder.length-1?"See results":"Next question"}</button>`:"";
    return `<div id="leadQuizPanel"><p class="lead-progress">Question ${state.quiz+1} of ${state.quizOrder.length} · ${escape(q.type.replaceAll("-"," "))}</p><h3 id="leadQuizPrompt">${escape(q.prompt)}</h3>${body}${feedback}</div>`;
  }
  function shell(){const tabs=[["guided","Guided"],["explore","Explore"],["cards","Flashcards"],["quiz","Quiz"]];return `<div class="card"><header class="lead-study-head"><div><h2 id="leadStudyTitle" tabindex="-1">📍 ${escape(D.title)}</h2><p>${escape(D.subtitle)}</p></div><button type="button" id="leadStudyBack" class="btn ghost">← All study modes</button></header><div class="lead-tabs" role="tablist" aria-label="Lead Placement Lab sections">${tabs.map(([id,label])=>`<button type="button" role="tab" id="lead-tab-${id}" data-tab="${id}" aria-controls="leadStudyMain" aria-selected="${state.tab===id}" tabindex="${state.tab===id?0:-1}">${label}</button>`).join("")}</div><main id="leadStudyMain" role="tabpanel" aria-labelledby="lead-tab-${state.tab}" tabindex="0">${state.tab==="guided"?guidedPanel():state.tab==="explore"?explorePanel():state.tab==="cards"?cardsPanel():quizPanel()}</main><p class="lead-attribution">Registered body surface and thoracic anatomy: BodyParts3D Release 4.0 / DBCLS, CC BY 4.0. <a href="${moduleBase}assets/ATTRIBUTION.md">Source, license, optimization and limitations</a>.</p></div>`;}
  function renderAll(){releaseView();root.innerHTML=shell();bind();if(state.tab==="guided"||state.tab==="explore"||(state.tab==="quiz"&&state.quizOrder.length&&!state.quizDone&&currentQuiz()?.type==="tap"))mount3D();}
  function activeLayers(){const quizTap=state.tab==="quiz"&&currentQuiz()?.type==="tap";return {...state.layers,body:state.bodySurface!=="hidden",leads:quizTap?false:state.layers.leads};}
  function applyViewerState(){view?.setLayers?.(activeLayers());view?.setBodyOpacity?.(state.bodySurface);}
  async function mount3D(){if(!use3D)return;const generation=viewGeneration,host=root.querySelector("#lead3DHost"),status=root.querySelector("#lead3DStatus"),fallback=root.querySelector("#lead2DFallback"),quizTap=state.tab==="quiz"&&currentQuiz()?.type==="tap";try{await loadAssets();if(generation!==viewGeneration)return;host.hidden=false;fallback.hidden=true;const instance=await window.LeadTorso3D.mount(host,{active:state.selected,highlights:quizTap?[]:highlights(),anchors:Object.fromEntries(D.leads.map((item)=>[item.id,item.anchor])),onSelect:(id,detail)=>selectMarker(id,detail),onSurfaceTap:(detail)=>{if(quizTap)pickQuiz({id:detail.nearest,point:detail.point});},onFailure:(message)=>fallbackTo2D(message)});if(generation!==viewGeneration){instance.dispose();return;}view=instance;applyViewerState();view.setTouch(state.touch);view.highlight(quizTap?[]:highlights());if(quizTap&&state.quizPicked!==null)view.showQuizResult({point:state.quizTapPoint,correctId:currentQuiz().target});status.textContent=quizTap?"3D placement question ready. Tap the anatomical surface; lead labels are hidden.":"3D torso ready. Front view preserves patient-right on the viewer's left.";}catch(error){if(generation!==viewGeneration)return;fallbackTo2D("3D unavailable. The native 2D placement reference remains active.");}}
  function fallbackTo2D(message){view?.dispose?.();view=null;use3D=false;const host=root.querySelector("#lead3DHost"),fallback=root.querySelector("#lead2DFallback"),status=root.querySelector("#lead3DStatus");if(host)host.hidden=true;if(fallback)fallback.hidden=false;if(status)status.textContent=message;bindMapMarkers();}
  function setStep(next){state.step=(next+D.guided.length)%D.guided.length;root.querySelector("#leadCurrentInfo")?.replaceWith(Object.assign(document.createElement("div"),{innerHTML:guideCard()}).firstElementChild);const old=root.querySelector(".lead-sequence");if(old)old.outerHTML=sequenceStrip();view?.highlight(highlights());bindStepButtons();}
  function selectMarker(id,detail){state.selected=id;view?.highlight([id]);if(state.tab==="quiz"&&currentQuiz()?.type==="tap")pickQuiz({id,point:detail?.modelPoint});if(state.tab==="explore"){const card=root.querySelector("#leadDetailCard");if(card)card.outerHTML=detailCard(id);root.querySelectorAll("[data-explore]").forEach((button)=>button.setAttribute("aria-pressed",String(button.dataset.explore===id)));}}
  function bindStepButtons(){root.querySelector("#leadPrevStep")?.addEventListener("click",()=>setStep(state.step-1));root.querySelector("#leadNextStep")?.addEventListener("click",()=>setStep(state.step+1));}
  function bindMapMarkers(){root.querySelectorAll("[data-map-marker]").forEach((button)=>button.addEventListener("click",()=>{const id=button.dataset.mapMarker;if(state.tab==="quiz"&&currentQuiz()?.type==="tap")pickQuiz({id});else selectMarker(id);}));}
  function flipCard(){state.cardFlipped=!state.cardFlipped;const card=root.querySelector("#leadFlashcard");card?.classList.toggle("is-flipped",state.cardFlipped);card?.setAttribute("aria-pressed",String(state.cardFlipped));}
  function moveCard(delta){state.card=(state.card+delta+state.cardOrder.length)%state.cardOrder.length;state.cardFlipped=false;renderAll();}
  function startQuiz(){state.quizOrder=shuffle(D.quiz.map((_,i)=>i));state.quiz=0;state.quizPicked=null;state.quizTapCorrect=null;state.quizTapPoint=null;state.quizScore=0;state.quizDone=false;renderAll();}
  function evaluateModelTap(targetId,point){const anchor=leadAnchor(targetId),target=anchor?.model;if(!Array.isArray(target)||target.length!==3||!Array.isArray(point)||point.length!==3)return null;const distance=Math.hypot(point[0]-target[0],point[1]-target[1],point[2]-target[2]);return distance<=(anchor.tolerance||0.12);}
  function pickQuiz(value){if(state.quizPicked!==null)return;const q=currentQuiz(),tap=value&&typeof value==="object"?value:{id:value},picked=tap.id??"surface";state.quizPicked=picked;if(q.type==="tap"){state.quizTapPoint=Array.isArray(tap.point)?tap.point:leadAnchor(picked)?.model||null;const pointResult=evaluateModelTap(q.target,state.quizTapPoint);state.quizTapCorrect=pointResult===null?picked===q.target:pointResult;}const correct=q.type==="tap"?state.quizTapCorrect:picked===q.answer;if(correct)state.quizScore++;renderAll();root.querySelector("#leadQuizFeedback")?.focus();}
  function nextQuiz(){if(state.quiz===state.quizOrder.length-1)state.quizDone=true;else{state.quiz++;state.quizPicked=null;state.quizTapCorrect=null;state.quizTapPoint=null;}renderAll();}
  function setCameraPreset(preset){if(view?.setView){view.setView(preset);return;}if(preset==="front"||preset==="reset"){view?.front?.();return;}const canvas=root.querySelector(".lead-3d-canvas"),key=preset==="left-oblique"?"ArrowLeft":"ArrowRight";for(let i=0;i<3;i++)canvas?.dispatchEvent(new KeyboardEvent("keydown",{key,bubbles:true}));}
  function bind(){
    root.querySelector("#leadStudyBack")?.addEventListener("click",()=>goHome());
    root.querySelectorAll("[data-tab]").forEach((button)=>{button.addEventListener("click",()=>{state.tab=button.dataset.tab;renderAll();root.querySelector(`[data-tab="${state.tab}"]`)?.focus();});button.addEventListener("keydown",(event)=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const tabs=Array.from(root.querySelectorAll("[data-tab]")),index=tabs.indexOf(button),next=event.key==="Home"?0:event.key==="End"?tabs.length-1:(index+(event.key==="ArrowRight"?1:-1)+tabs.length)%tabs.length;tabs[next].click();});});
    root.querySelectorAll("[data-layer]").forEach((input)=>input.addEventListener("change",()=>{state.layers[input.dataset.layer]=input.checked;applyViewerState();}));
    root.querySelector("#leadBodySurface")?.addEventListener("change",(event)=>{state.bodySurface=event.target.value;state.layers.body=state.bodySurface!=="hidden";applyViewerState();});
    root.querySelectorAll("[data-view-preset]").forEach((button)=>button.addEventListener("click",()=>setCameraPreset(button.dataset.viewPreset)));root.querySelector("#leadZoomIn")?.addEventListener("click",()=>view?.zoom(-.3));root.querySelector("#leadZoomOut")?.addEventListener("click",()=>view?.zoom(.3));
    root.querySelector("#leadTouchToggle")?.addEventListener("click",(event)=>{state.touch=!state.touch;view?.setTouch(state.touch);event.currentTarget.setAttribute("aria-pressed",String(state.touch));event.currentTarget.textContent=state.touch?"Unlock page scrolling":"Enable touch rotation";});
    bindStepButtons();bindMapMarkers();
    root.querySelectorAll("[data-explore]").forEach((button)=>button.addEventListener("click",()=>selectMarker(button.dataset.explore)));
    root.querySelector("#leadFlashcard")?.addEventListener("click",flipCard);root.querySelector("#leadFlashcard")?.addEventListener("keydown",(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();flipCard();}});root.querySelector("#leadCardFlip")?.addEventListener("click",flipCard);root.querySelector("#leadCardPrev")?.addEventListener("click",()=>moveCard(-1));root.querySelector("#leadCardNext")?.addEventListener("click",()=>moveCard(1));
    root.querySelector("#leadCardReverse")?.addEventListener("click",()=>{state.cardReverse=!state.cardReverse;state.cardFlipped=false;renderAll();});root.querySelector("#leadCardShuffle")?.addEventListener("click",()=>{state.cardOrder=shuffle(state.cardOrder);state.card=0;state.cardFlipped=false;renderAll();});
    root.querySelector("#leadQuizStart")?.addEventListener("click",startQuiz);root.querySelectorAll("[data-quiz-opt]").forEach((button)=>button.addEventListener("click",()=>pickQuiz(Number(button.dataset.quizOpt))));root.querySelector("#leadQuizNext")?.addEventListener("click",nextQuiz);
  }
  root.addEventListener("keydown",(event)=>{if(root.classList.contains("hidden"))return;if(event.target?.matches("input,select,textarea,.lead-3d-canvas"))return;if(state.tab==="cards"&&event.key==="ArrowRight"){event.preventDefault();moveCard(1);}if(state.tab==="cards"&&event.key==="ArrowLeft"){event.preventDefault();moveCard(-1);}});
  return {open,data:D,getState:()=>state,selectMarker,setStep,startQuiz,getTapTarget:(id)=>leadAnchor(id),evaluateModelTap};
})();
