/* Lead Placement Lab. Isolated runtime injection; no changes to global quiz scoring. */
"use strict";
const LeadPlacementLab = (() => {
  const D=typeof LEAD_PLACEMENT!=="undefined"?LEAD_PLACEMENT:null;
  const home=document.getElementById("home"),menu=document.getElementById("homeMenu");
  if(!D||!home||!menu){console.warn("Lead Placement Lab did not initialize.");return null;}
  const root=document.createElement("section");root.id="leadPlacementHome";root.className="hidden lead-study";root.setAttribute("aria-labelledby","leadStudyTitle");home.append(root);
  const moduleBase=new URL(".",document.currentScript.src).href;
  const escape=(value)=>String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const shuffle=(items)=>{const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  const state={tab:"guided",step:0,selected:"v1",layers:{body:true,skeleton:true,muscle:false,landmarks:true,leads:true},bodySurface:"translucent",touch:false,card:0,cardOrder:D.cards.map((_,i)=>i),cardReverse:false,cardFlipped:false,quizOrder:[],quiz:0,quizPicked:null,quizScore:0,quizDone:false};
  let view=null,viewGeneration=0,assetPromise=null,use3D=true;

  const launch=document.createElement("button");launch.className="btn secondary";launch.type="button";launch.id="leadPlacementLaunch";launch.append(document.createTextNode("📍 Lead Placement Lab"));const sub=document.createElement("small");sub.textContent=D.subtitle;launch.append(sub);launch.addEventListener("click",open);
  const rhythmButton=Array.from(menu.querySelectorAll("button")).find((button)=>/ECG Rhythm Practice/.test(button.textContent||""));menu.insertBefore(launch,rhythmButton||null);
  const oldHome=goHome;goHome=function(){releaseView();root.classList.add("hidden");home.classList.remove("lead-study-active");oldHome();};
  document.addEventListener("visibilitychange",()=>{if(!document.hidden)view?.draw?.();});

  function scriptFile(path){return new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=moduleBase+path;script.onload=resolve;script.onerror=()=>{script.remove();reject(new Error("Lead-placement asset unavailable"));};document.head.append(script);});}
  function loadAssets(){if(!assetPromise)assetPromise=(async()=>{if(!window.EcgThree)await scriptFile("../ecg-study/vendor/three-gltf.min.js");if(!window.LeadTorsoModelData)await scriptFile("assets/torso-model-data.js");if(!window.LeadTorso3D)await scriptFile("torso-3d.js");})().catch((error)=>{assetPromise=null;throw error;});return assetPromise;}
  function releaseView(){viewGeneration++;view?.dispose?.();view=null;}
  function open(){goHome();if(typeof khHideAll==="function")khHideAll();hide("homeMenu");show("home");show("leadPlacementHome");home.classList.add("lead-study-active");renderAll();window.scrollTo(0,0);root.querySelector("#leadStudyTitle")?.focus();}

  function leadById(id){return D.leads.find((item)=>item.id===id)||D.limbViews.find((item)=>item.id===id)||D.landmarks.find((item)=>item.id===id);}
  function allExploreItems(){return [...D.leads,...D.limbViews,...D.landmarks];}
  function highlights(){return state.tab==="guided"?D.guided[state.step].highlights:[state.selected];}
  function layerControls(){return `<fieldset class="lead-layer-controls"><legend>Layers</legend>${[["body","Body"],["skeleton","Skeleton"],["muscle","Muscle"],["landmarks","Landmarks"],["leads","Leads"]].map(([id,label])=>`<label><input type="checkbox" data-layer="${id}" ${state.layers[id]?"checked":""}> ${label}</label>`).join("")}<label>Body surface <select id="leadBodySurface" aria-label="Body surface opacity"><option value="translucent" ${state.bodySurface==="translucent"?"selected":""}>Translucent</option><option value="opaque" ${state.bodySurface==="opaque"?"selected":""}>Opaque</option></select></label></fieldset>`;}
  function viewControls(){return `<div class="lead-view-controls" role="group" aria-label="3D view controls"><button type="button" id="leadFrontView">Front view</button><button type="button" id="leadZoomIn" aria-label="Zoom in">Zoom +</button><button type="button" id="leadZoomOut" aria-label="Zoom out">Zoom −</button><button type="button" id="leadTouchToggle" aria-pressed="${state.touch}">${state.touch?"Unlock page scrolling":"Enable touch rotation"}</button></div>`;}
  function placementFigure(classes="",buttons=true){
    const pos={v1:[43,43],v2:[51,43],v3:[57,51],v4:[63,58],v5:[74,58],v6:[84,58],ra:[13,25],la:[87,25],rl:[22,88],ll:[78,88]};
    const markers=buttons?Object.entries(pos).map(([id,[x,y]])=>`<button type="button" class="lead-map-marker" data-map-marker="${id}" style="left:${x}%;top:${y}%" aria-label="${id.toUpperCase()} location">${id.toUpperCase()}</button>`).join(""):"";
    return `<div class="lead-map ${classes}" role="img" aria-label="Front-facing torso placement diagram"><svg viewBox="0 0 300 380" aria-hidden="true"><path class="lead-map-body" d="M88 42 Q115 18 150 20 Q185 18 212 42 L260 82 Q245 118 224 126 L216 348 Q184 366 150 368 Q116 366 84 348 L76 126 Q55 118 40 82 Z"/><path class="lead-map-sternum" d="M150 78 L150 235"/><path class="lead-map-clavicle" d="M150 82 Q118 68 88 86 M150 82 Q182 68 212 86"/>${[112,139,166,193,220,247].map((y,i)=>`<path class="lead-map-rib" d="M150 ${y} Q${112-i*3} ${y-12} ${78-i*2} ${y+8} M150 ${y} Q${188+i*3} ${y-12} ${222+i*2} ${y+8}"/>`).join("")}<path class="lead-map-line" d="M188 75 L188 270 M222 90 L222 270 M248 106 L248 270"/><text x="188" y="292">MCL</text><text x="222" y="310">AAL</text><text x="248" y="328">MAL</text></svg>${markers}<span class="lead-map-side left">PATIENT RIGHT</span><span class="lead-map-side right">PATIENT LEFT</span></div>`;
  }
  function sequenceStrip(){return `<div class="lead-sequence" aria-label="Preferred chest lead placement sequence">${D.chestSequence.map((id,i)=>`<span data-seq="${id}" class="${highlights().includes(id)?"active":""}">${id.toUpperCase()}</span>${i<D.chestSequence.length-1?"<b aria-hidden=\"true\">→</b>":""}`).join("")}</div>`;}
  function viewer(){return `<div class="lead-view-shell">${layerControls()}${viewControls()}<p id="lead3DStatus" class="lead-status" role="status">${use3D?"Loading local 3D torso…":"Using the native 2D placement diagram."}</p><div id="lead3DHost" class="lead-3d-host" hidden></div><div id="lead2DFallback" ${use3D?"hidden":""}>${placementFigure("lead-fallback-map")}</div><p class="lead-orientation"><strong>${escape(D.patient.note)}</strong> Reset to Front view after rotating.</p><p class="lead-help">Mouse drag rotates. Touch scrolls by default; enable touch rotation for orbit and pinch, then unlock scrolling. Arrow keys rotate when the torso has focus. Skeleton, muscle, landmark lines and electrodes are schematic teaching overlays.</p></div>`;}
  function guideCard(){const item=D.guided[state.step];return `<article class="lead-info-card" id="leadCurrentInfo"><p class="lead-step">Step ${state.step+1} of ${D.guided.length}</p><h3>${escape(item.lead)}</h3><dl><div><dt>Exact placement</dt><dd>${escape(item.placement)}</dd></div><div><dt>Memory cue</dt><dd>${escape(item.cue)}</dd></div></dl><div class="lead-step-controls"><button type="button" id="leadPrevStep">Previous</button><button type="button" id="leadNextStep">${state.step===D.guided.length-1?"Start again":"Next"}</button></div></article>`;}
  function guidedPanel(){return `<div id="leadGuidedPanel">${viewer()}${guideCard()}${sequenceStrip()}</div>`;}
  function detailCard(id=state.selected){const item=leadById(id)||leadById("v1");const isLandmark=D.landmarks.some((x)=>x.id===item.id);return `<article class="lead-info-card" id="leadDetailCard" aria-live="polite"><h3>${escape(item.name)}</h3><dl><div><dt>${isLandmark?"Definition":"Placement / direction"}</dt><dd>${escape(item.placement)}</dd></div>${item.landmark?`<div><dt>Landmark</dt><dd>${escape(item.landmark)}</dd></div>`:""}${item.plane?`<div><dt>Plane</dt><dd>${escape(item.plane)}</dd></div>`:""}${item.side?`<div><dt>Patient orientation</dt><dd>${escape(item.side)}</dd></div>`:""}<div><dt>Memory cue</dt><dd>${escape(item.mnemonic)}</dd></div></dl></article>`;}
  function explorePanel(){const groups=[["Chest leads",D.leads.filter((x)=>x.family==="chest")],["Limb electrodes",D.leads.filter((x)=>x.family==="limb")],["Limb lead views",D.limbViews],["Landmarks",D.landmarks]];return `<div id="leadExplorePanel">${viewer()}<div class="lead-explore-picker">${groups.map(([label,items])=>`<fieldset><legend>${label}</legend>${items.map((item)=>`<button type="button" data-explore="${item.id}" aria-pressed="${state.selected===item.id}">${escape(item.name)}</button>`).join("")}</fieldset>`).join("")}</div>${detailCard()}${sequenceStrip()}</div>`;}
  function thumb(id){const coords={v1:[43,38],v2:[50,38],v3:[57,49],v4:[64,59],v5:[76,59],v6:[86,59]},p=coords[id]||[64,59];return `<svg class="lead-card-thumb" viewBox="0 0 180 150" role="img" aria-label="Front torso thumbnail highlighting ${escape(id.toUpperCase())}"><path d="M55 18 Q90 2 125 18 L156 44 L139 140 H41 L24 44 Z"/><path d="M90 28 L90 112 M90 32 Q68 25 50 38 M90 32 Q112 25 130 38"/><circle cx="${p[0]*1.8}" cy="${p[1]*1.5}" r="7"/><text x="${p[0]*1.8}" y="${p[1]*1.5+3}" text-anchor="middle">${escape(id.toUpperCase())}</text></svg>`;}
  function cardsPanel(){const index=state.cardOrder[state.card],card=D.cards[index],front=state.cardReverse?card.definition:card.term,back=state.cardReverse?card.term:card.definition;return `<div id="leadCardsPanel"><p class="lead-progress">Card ${state.card+1} of ${D.cards.length}</p><div class="lead-card-tools"><button type="button" id="leadCardReverse" aria-pressed="${state.cardReverse}">Show definitions first</button><button type="button" id="leadCardShuffle">Shuffle</button></div><div class="lead-flashcard${state.cardFlipped?" is-flipped":""}" id="leadFlashcard" role="button" tabindex="0" aria-pressed="${state.cardFlipped}" aria-label="Flashcard; activate to flip"><div class="lead-card-face lead-card-front"><small>${state.cardReverse?"Definition":"Term"}</small>${card.visual?thumb(card.visual):""}<strong id="leadCardFront">${escape(front)}</strong></div><div class="lead-card-face lead-card-back"><small>${state.cardReverse?"Term":"Definition"}</small><strong id="leadCardBack">${escape(back)}</strong></div></div><div class="lead-card-nav"><button type="button" id="leadCardPrev">Previous</button><button type="button" id="leadCardFlip">Flip</button><button type="button" id="leadCardNext">Next</button></div><p class="lead-help">Reverse mode swaps each fact instead of duplicating it. Chest-placement cards include a schematic thumbnail.</p></div>`;}

  function currentQuiz(){return D.quiz[state.quizOrder[state.quiz]];}
  function quizDiagram(q){const selected=state.quizPicked,answered=selected!==null;return `<div class="lead-quiz-map" data-correct="${answered?q.target:""}" data-selected="${answered?selected:""}">${placementFigure("",true)}</div>`;}
  function quizPanel(){
    if(!state.quizOrder.length)return `<div id="leadQuizPanel"><p>Practice chest locations, landmarks, lead pairings, augmented directions and frontal versus transverse views. Feedback appears immediately.</p><button type="button" id="leadQuizStart" class="btn">Start quiz (${D.quiz.length} questions)</button></div>`;
    if(state.quizDone){const total=state.quizOrder.length,pct=Math.round(state.quizScore/total*100);return `<div id="leadQuizPanel"><h3>Quiz results</h3><div class="score-circle ${pct>=80?"pass":"fail"}"><span class="pct">${pct}%</span><span class="lbl">${state.quizScore} / ${total}</span></div><button type="button" id="leadQuizStart" class="btn">Retake quiz</button></div>`;}
    const q=currentQuiz(),answered=state.quizPicked!==null,isTap=q.type==="tap";let body="";
    if(isTap)body=quizDiagram(q);else{if(q.type==="identify")body=placementFigure("lead-identify-map",false).replace("</div>",`<span class="lead-identify-dot" data-highlight="${q.highlight}">${q.highlight.toUpperCase()}</span></div>`);body+=`<div class="lead-quiz-options">${q.options.map((option,i)=>{let cls="";if(answered&&i===q.answer)cls="correct";else if(answered&&i===state.quizPicked)cls="wrong";return `<button type="button" data-quiz-opt="${i}" class="${cls}" ${answered?"disabled":""}>${escape(option)}</button>`;}).join("")}</div>`;}
    const correct=answered&&(isTap?state.quizPicked===q.target:state.quizPicked===q.answer);const feedback=answered?`<div class="lead-feedback ${correct?"correct":"wrong"}" id="leadQuizFeedback" tabindex="-1"><strong>${correct?"Correct":"Not quite"}</strong><p>${escape(q.explain)}</p></div><button type="button" id="leadQuizNext" class="btn">${state.quiz===state.quizOrder.length-1?"See results":"Next question"}</button>`:"";
    return `<div id="leadQuizPanel"><p class="lead-progress">Question ${state.quiz+1} of ${state.quizOrder.length} · ${escape(q.type.replaceAll("-"," "))}</p><h3 id="leadQuizPrompt">${escape(q.prompt)}</h3>${body}${feedback}</div>`;
  }
  function shell(){return `<div class="card"><header class="lead-study-head"><div><h2 id="leadStudyTitle" tabindex="-1">📍 ${escape(D.title)}</h2><p>${escape(D.subtitle)}</p></div><button type="button" id="leadStudyBack" class="btn ghost">← All study modes</button></header><div class="lead-tabs" role="tablist" aria-label="Lead Placement Lab sections">${[["guided","Guided"],["explore","Explore"],["cards","Flashcards"],["quiz","Quiz"]].map(([id,label])=>`<button type="button" role="tab" data-tab="${id}" aria-selected="${state.tab===id}">${label}</button>`).join("")}</div><main id="leadStudyMain" role="tabpanel">${state.tab==="guided"?guidedPanel():state.tab==="explore"?explorePanel():state.tab==="cards"?cardsPanel():quizPanel()}</main><p class="lead-attribution">Body surface: HuBMAP Human Reference Atlas / Visible Human Male v1.2, CC BY 4.0. <a href="${moduleBase}assets/ATTRIBUTION.md">Source, license, optimization and limitations</a>.</p></div>`;}
  function renderAll(){releaseView();root.innerHTML=shell();bind();if(state.tab==="guided"||state.tab==="explore")mount3D();}
  async function mount3D(){if(!use3D)return;const generation=viewGeneration,host=root.querySelector("#lead3DHost"),status=root.querySelector("#lead3DStatus"),fallback=root.querySelector("#lead2DFallback");try{await loadAssets();if(generation!==viewGeneration)return;host.hidden=false;fallback.hidden=true;const instance=await window.LeadTorso3D.mount(host,{active:state.selected,highlights:highlights(),onSelect:(id)=>selectMarker(id),onFailure:(message)=>fallbackTo2D(message)});if(generation!==viewGeneration){instance.dispose();return;}view=instance;view.setLayers(state.layers);view.setBodyOpacity(state.bodySurface);view.setTouch(state.touch);view.highlight(highlights());status.textContent="3D torso ready. Front view preserves patient-right on the viewer's left.";}catch(error){if(generation!==viewGeneration)return;fallbackTo2D("3D unavailable. The native 2D placement diagram remains active.");}}
  function fallbackTo2D(message){view?.dispose?.();view=null;use3D=false;const host=root.querySelector("#lead3DHost"),fallback=root.querySelector("#lead2DFallback"),status=root.querySelector("#lead3DStatus");if(host)host.hidden=true;if(fallback)fallback.hidden=false;if(status)status.textContent=message;bindMapMarkers();}
  function setStep(next){state.step=(next+D.guided.length)%D.guided.length;root.querySelector("#leadCurrentInfo")?.replaceWith(Object.assign(document.createElement("div"),{innerHTML:guideCard()}).firstElementChild);const old=root.querySelector(".lead-sequence");if(old)old.outerHTML=sequenceStrip();view?.highlight(highlights());bindStepButtons();}
  function selectMarker(id){state.selected=id;view?.highlight([id]);if(state.tab==="explore"){const card=root.querySelector("#leadDetailCard");if(card)card.outerHTML=detailCard(id);root.querySelectorAll("[data-explore]").forEach((button)=>button.setAttribute("aria-pressed",String(button.dataset.explore===id)));}}
  function bindStepButtons(){root.querySelector("#leadPrevStep")?.addEventListener("click",()=>setStep(state.step-1));root.querySelector("#leadNextStep")?.addEventListener("click",()=>setStep(state.step+1));}
  function bindMapMarkers(){root.querySelectorAll("[data-map-marker]").forEach((button)=>button.addEventListener("click",()=>{const id=button.dataset.mapMarker;if(state.tab==="quiz"&&currentQuiz()?.type==="tap")pickQuiz(id);else selectMarker(id);}));}
  function flipCard(){state.cardFlipped=!state.cardFlipped;const card=root.querySelector("#leadFlashcard");card?.classList.toggle("is-flipped",state.cardFlipped);card?.setAttribute("aria-pressed",String(state.cardFlipped));}
  function moveCard(delta){state.card=(state.card+delta+state.cardOrder.length)%state.cardOrder.length;state.cardFlipped=false;renderAll();}
  function startQuiz(){state.quizOrder=shuffle(D.quiz.map((_,i)=>i));state.quiz=0;state.quizPicked=null;state.quizScore=0;state.quizDone=false;renderAll();}
  function pickQuiz(value){if(state.quizPicked!==null)return;const q=currentQuiz();state.quizPicked=value;const correct=q.type==="tap"?value===q.target:value===q.answer;if(correct)state.quizScore++;renderAll();root.querySelector("#leadQuizFeedback")?.focus();}
  function nextQuiz(){if(state.quiz===state.quizOrder.length-1)state.quizDone=true;else{state.quiz++;state.quizPicked=null;}renderAll();}
  function bind(){
    root.querySelector("#leadStudyBack")?.addEventListener("click",()=>goHome());
    root.querySelectorAll("[data-tab]").forEach((button)=>button.addEventListener("click",()=>{state.tab=button.dataset.tab;renderAll();}));
    root.querySelectorAll("[data-layer]").forEach((input)=>input.addEventListener("change",()=>{state.layers[input.dataset.layer]=input.checked;view?.setLayers(state.layers);}));
    root.querySelector("#leadBodySurface")?.addEventListener("change",(event)=>{state.bodySurface=event.target.value;view?.setBodyOpacity(state.bodySurface);});
    root.querySelector("#leadFrontView")?.addEventListener("click",()=>view?.front());root.querySelector("#leadZoomIn")?.addEventListener("click",()=>view?.zoom(-.3));root.querySelector("#leadZoomOut")?.addEventListener("click",()=>view?.zoom(.3));
    root.querySelector("#leadTouchToggle")?.addEventListener("click",(event)=>{state.touch=!state.touch;view?.setTouch(state.touch);event.currentTarget.setAttribute("aria-pressed",String(state.touch));event.currentTarget.textContent=state.touch?"Unlock page scrolling":"Enable touch rotation";});
    bindStepButtons();bindMapMarkers();
    root.querySelectorAll("[data-explore]").forEach((button)=>button.addEventListener("click",()=>selectMarker(button.dataset.explore)));
    root.querySelector("#leadFlashcard")?.addEventListener("click",flipCard);root.querySelector("#leadFlashcard")?.addEventListener("keydown",(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();flipCard();}});root.querySelector("#leadCardFlip")?.addEventListener("click",flipCard);root.querySelector("#leadCardPrev")?.addEventListener("click",()=>moveCard(-1));root.querySelector("#leadCardNext")?.addEventListener("click",()=>moveCard(1));
    root.querySelector("#leadCardReverse")?.addEventListener("click",()=>{state.cardReverse=!state.cardReverse;state.cardFlipped=false;renderAll();});root.querySelector("#leadCardShuffle")?.addEventListener("click",()=>{state.cardOrder=shuffle(state.cardOrder);state.card=0;state.cardFlipped=false;renderAll();});
    root.querySelector("#leadQuizStart")?.addEventListener("click",startQuiz);root.querySelectorAll("[data-quiz-opt]").forEach((button)=>button.addEventListener("click",()=>pickQuiz(Number(button.dataset.quizOpt))));root.querySelector("#leadQuizNext")?.addEventListener("click",nextQuiz);
  }
  root.addEventListener("keydown",(event)=>{if(root.classList.contains("hidden"))return;if(event.target?.matches("input,select,textarea,.lead-3d-canvas"))return;if(state.tab==="cards"&&event.key==="ArrowRight"){event.preventDefault();moveCard(1);}if(state.tab==="cards"&&event.key==="ArrowLeft"){event.preventDefault();moveCard(-1);}});
  return {open,data:D,getState:()=>state,selectMarker,setStep,startQuiz};
})();
